# Generated by Django 4.2 on 2023-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, unique=True)),
                ('Text', models.TextField(max_length=255)),
                ('Created_At', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=255)),
                ('Notes_Title', models.ManyToManyField(to='two_models.notes')),
            ],
        ),
    ]
